spring:
  sql:
      init:
        mode: always
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create
      defer-datasource-initialization: true
      show-sql: true
      open-in-view: false
      properties:
        hibernate:
          format_sql: true
